spring:
  application:
    name: eureka_client_ribbon
server:
  port: 1000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
  instance:
    status-page-url: http://localhost:${server.port}/swagger-ui.html
management:
  endpoints:
    web:
      base-path: /actuator